Some of the akhq routes were incorrectly resolved as  default (nk) route
TouK/nussknacker pull request #1562
Opened 2021-05-05 12:19 UTC by ZbyszekMM

Some of the akhq routes were incorrectly resolved as  default (nk) route, just a little nuisance.

2021-05-06 07:57 UTC, lciolecki approved these changes
Good job!

2021-05-06 08:29 UTC, gadomsky commented on demo/docker/nginx/nginx.conf
> +    }
If we had Apache we could handle relative redirects with `ProxyPassReverse`, but nginx does not have it.
But I found on the Web https://www.nginx.com/resources/wiki/start/topics/examples/likeapache/
Would it be any good in this case?

2021-05-06 09:04 UTC, mproch requested changes
Let's upgrade to AKHQ 0.17 with fix instead:
https://github.com/tchiotludo/akhq/issues/469

2021-05-07 09:06 UTC, closed without merging

2021-05-07 09:06 UTC, ZbyszekMM commented
Performed upgrade of akhq to 0.17 in a separate PR