Grafana dashboard corrections
TouK/nussknacker pull request #1723
Opened 2021-05-31 07:09 UTC by ZbyszekMM

Changed treatment of null metric values on the graph. Instead of extrapolating values  with a straight  line ("connect"), simply do not show anything in the time period when there were no metrics reported. The result is hopefully on the attached pic.
![image](https://user-images.githubusercontent.com/50945192/120152852-4c374580-c1ee-11eb-8494-9df5a5c2cc56.png).

Additionally modified  the "max lag" graph , we were showing stacked sum of max lags as reported by each Flink parallelized task. This is roughly the same value shown and stacked as many times as the Flink task parallelism level. Decided to show only one value, commented the graph accordingly. 

An interesting new effect is visible - every 4 minutes reporting (hopefully only reporting) stops for ca 20s, I get this effect on both my local machine and client (N..a) deployment.

2021-05-31 08:21 UTC, arkadius approved these changes
Good job, let's merge it!

2021-05-31 10:19 UTC, piotrp requested changes

2021-05-31 10:19 UTC, piotrp commented on demo/docker/grafana/dashboards/Flink-ESP.json
> +      "description": "IMPORTANT. \nThis metrics does NOT show the overall lag on Kafka source; a largest lag among all the source partitions is shown. ",
"This metrics" -> "This metric", and while we're changing it we may remove unnecessary space at end :D

2021-06-01 13:51 UTC, ZbyszekMM commented
Applied piotrp review comments.
Additional changes: the core of this PR is not to invent values when there are no metrics reported. In majority of cases the graphs look much more credible. There is one side effect though - from time to time, time difference between consecutive metrics is slightly above 10s resulting in "null value" and disconnected line on the graph. This is disturbing to the viewer, because one might think something wrong is going here. This effect becomes less and less visible when the observation "interval"  is higher, becoming not visible at all with interval set to 3 minutes. 
So, seeing some value in the observation interval of 10s, I set the default one to 30s and added 3 minute one. 
Finally, tuned up telegraf config to let it deal with a bit higher than very low number of metrics (_Metric buffer overflow; XYZ metrics have been dropped_ .

2021-06-01 14:15 UTC, piotrp approved these changes

2021-06-02 08:12 UTC, merged