Component drag preview
TouK/nussknacker pull request #2213
Opened 2021-09-16 15:39 UTC by JulianWielga

2021-09-17 09:38 UTC, JulianWielga commented
https://user-images.githubusercontent.com/965924/133761826-0b74e278-c71e-4f06-be66-60f9413ed1e5.mov

2021-09-21 08:14 UTC, mproch requested changes
Let's change base branch to staging

2021-09-23 08:45 UTC, arkadius approved these changes

2021-09-23 09:18 UTC, mproch approved these changes
:+1:

2021-09-23 09:18 UTC, merged