Rename branch to union in scenario builder
TouK/nussknacker pull request #2914
Opened 2022-03-04 08:41 UTC by dswiecki

2022-03-04 12:11 UTC, mproch approved these changes

2022-03-04 12:21 UTC, arkadius commented on scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
> +  @silent("deprecated")
branch should use join - not otherwise

2022-03-04 12:21 UTC, arkadius requested changes
please fix one thing

2022-03-04 14:50 UTC, arkadius approved these changes

2022-03-16 08:12 UTC, dswiecki commented on scenario-api/src/main/scala/pl/touk/nussknacker/engine/build/GraphBuilder.scala
> +  @silent("deprecated")
done

2022-03-16 09:07 UTC, merged