Fix: ProcessService should return only not archived scenarios
TouK/nussknacker pull request #3007
Opened 2022-04-13 15:04 UTC by lciolecki

2022-04-13 18:45 UTC, JulianWielga requested changes
I think it's FE problem

2022-04-13 18:51 UTC, lciolecki commented
> I think it's FE problem

Why do you think that?

2022-04-14 06:28 UTC, mproch approved these changes
@JulianWielga this should be handled on BE... we should just ignore archived scenarios...

2022-04-14 08:08 UTC, JulianWielga approved these changes

2022-04-14 08:57 UTC, merged