Fix form types in properties (parallelism and async interpretation)
TouK/nussknacker pull request #4210
Opened 2023-04-03 11:41 UTC by mslabek

Typing a non-integer value in the parallelism or async interpretation properties resulted in an ugly looking backend unmarshalling error since backend expects an integer/long in these fields. There doesn't seem to be a way to get types and default values of type specific scenario properties without modifying the backend api. The simplest solution is to prevent the user from typing non-integers.

The form with new placeholders looks like this:
![Screenshot_20230403_133403](https://user-images.githubusercontent.com/92804917/229497774-1b25e7b7-f27e-4d82-85cb-d397bdf13528.png)

There is no feedback to the user when he tries to type a non-integer, but that is still preferable than throwing an ugly error.

2023-04-05 13:30 UTC, JulianWielga commented on designer/client/components/graph/node-modal/editors/field/Field.tsx
> +    const optionIsNull = x.value === null && value === undefined
?

2023-04-07 08:35 UTC, lciolecki commented
But what about validating it on the backend side? I think we should also validate it on the backend and return a nice message.

2023-04-07 11:13 UTC, arkadius commented on designer/client/components/graph/node-modal/properties.tsx
> +                fieldLabel={"I/O mode"}
It shouldn't be done on FE, we should move this to BE, we already has options to do that. Let's talk

2023-04-07 11:15 UTC, arkadius requested changes
This change explores the direction of static scenario definitions on FE side, that we are trying to get rid of

2023-04-12 15:24 UTC, mslabek commented
Thanks for feedback. I'm taking a new approach to this problem in line with your suggestions. The WIP PR: https://github.com/TouK/nussknacker/pull/4225

2023-04-12 15:24 UTC, closed without merging