Imiges comparing
TouK/nussknacker pull request #4552
Opened 2023-08-03 17:37 UTC by lodyczekoladowe

2023-08-17 14:22 UTC, JulianWielga requested changes

2023-08-18 08:50 UTC, lodyczekoladowe commented on designer/client/cypress/tsconfig.json
> +        "lib": ["es5", "dom", "ES2021.String"],
no

2023-08-18 08:51 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +        cy.get('[title="layout"] > .ToolbarButton--icon--w9M5n').click();
okey

2023-08-18 08:57 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +        cy.get('[title="Name"]').click();
no, the point is to make the cursor stop flashing

2023-08-18 08:58 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +    cy.get(padding ? ".joint-layers" : '[data-testid="window-frame"]').matchImage({
okey

2023-08-18 08:59 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +    const basePath = "/home/fgl/Git/nussknacker/docs/scenarios_authoring/img/imagesComparing/";
i dont know how to fix that

2023-08-18 08:59 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +function imageTake(padding = false) {
okey

2023-08-18 12:44 UTC, lodyczekoladowe commented on designer/client/cypress/e2e/imagesComparing.cy.ts
> +        cy.viewport(1920, 1080);
however it has to be

2023-08-22 11:59 UTC, lodyczekoladowe commented on CONTRIBUTING.md
@ZbyszekMM Is it okey?

2023-08-22 12:31 UTC, JulianWielga approved these changes

2023-08-22 14:29 UTC, JulianWielga requested changes

2023-08-23 12:56 UTC, ZbyszekMM requested changes

2023-08-24 10:20 UTC, ZbyszekMM commented on CONTRIBUTING.md
> +2. **Image Storage**: All captured images are stored in the `docs/autoImageChangeDocs` folder. These images are named according to a specific convention:
specific --> following

2023-08-25 10:53 UTC, JulianWielga approved these changes

2023-08-25 10:54 UTC, merged