[NU-1291] [Security] Processing type data - check read access to category
TouK/nussknacker pull request #5141
Opened 2023-12-04 12:41 UTC by arkadius

## Describe your changes

## Checklist before merge
- [x] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [x] Code is cleaned from temporary changes and commented out lines
- [x] Parts of the code that are not easy to understand are documented in the code
- [x] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [x] Documentation added or updated
- [x] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [x] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

2023-12-04 21:10 UTC, pielas requested changes
I think it would be generally

2023-12-04 21:10 UTC, pielas commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/services/AppApiHttpService.scala
> +          //       We should consider authorization of access to this data
```suggestion
          //       We should consider adding an authorization of access rights to this data.
```

2023-12-04 21:10 UTC, pielas commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/statistics/UsageStatisticsReportsSettingsDeterminer.scala
> +    //       given user has no access.
```suggestion
    //       given user has no access rights.
```

2023-12-05 07:24 UTC, arkadius commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/processingtypedata/ProcessingTypeDataProvider.scala
> +  // TODO: We should return type that can produce views for users with access to certain categories. Thanks to that
I haven't in mind `ProcessingType` here. It was about generic parameter `C` (for combined type). I'll change it a bit to make it more clear.

2023-12-05 07:49 UTC, pielas approved these changes
LGTM

2023-12-05 08:03 UTC, merged