[NU-1513] search panel
TouK/nussknacker pull request #5736
Opened 2024-03-14 22:08 UTC by JulianWielga

## Describe your changes

[NU-1513]

## Checklist before merge
- [ ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ ] Code is cleaned from temporary changes and commented out lines
- [ ] Parts of the code that are not easy to understand are documented in the code
- [ ] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [ ] Documentation added or updated
- [ ] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [ ] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

2024-03-19 09:13 UTC, Dzuming requested changes

2024-03-19 09:13 UTC, Dzuming commented on designer/client/src/components/toolbars/search/utils.ts
> +                        .concat(edges.length ? "edgeExpression" : null)
If i understand correctly, edgeExpression is also a field, but it's not a part of findFields logic. Maybe it's worth to have this findFields logic in one place, and move edgeExpression calculation inside of the findFIelds?

2024-03-19 10:16 UTC, JulianWielga commented on designer/client/src/components/graph/node-modal/NodeDetailsContent.tsx
> +            {userSettings["debug.nodesAsJson"] && <DebugNodeInspector node={node} />}
starting in dev mode shows new panel/toolbar. just add flag there.

2024-03-25 09:35 UTC, JulianWielga commented on designer/client/src/components/graph/Graph.tsx
> +styles;
Added issue for that (NU-1559)

2024-03-25 09:42 UTC, JulianWielga commented on designer/client/src/components/toolbars/search/utils.ts
> +const fieldsSelectors: FilterSelector = [
this is for next stages if ever

2024-03-25 10:44 UTC, Dzuming approved these changes

2024-03-25 11:55 UTC, merged