[NU-1806] Add activity parameters
TouK/nussknacker pull request #6860
Opened 2024-09-13 11:39 UTC by gskrobisz

## Describe your changes

## Checklist before merge
- [ ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ ] Code is cleaned from temporary changes and commented out lines
- [ ] Parts of the code that are not easy to understand are documented in the code
- [ ] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [ ] Documentation added or updated
- [ ] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [ ] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

2024-12-20 11:12 UTC, mgoworko commented on common-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/FixedExpressionValue.scala
> +  def apply(expression: String, label: String): FixedExpressionValue = FixedExpressionValue(expression, label, None)
Is this apply method required? In code itself it is not required, because there is default value for hintText, but maybe I'm missing sth related to some integrations/Flink/Java.

2024-12-20 11:12 UTC, mgoworko commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/component/NodesDeploymentData.scala
> +  type NodeDeploymentData = Map[String, String]
I think it should be a final case class, serializable to JSON. Now it is a map, serializable to Json object. So adding any new field beside the map of raw params would break compatibility

2024-12-20 11:12 UTC, mgoworko commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +  implicit val fixedValuesParameterEditorDecoder: Decoder[FixedValuesParameterEditor] = { (c: HCursor) =>
suggestion:

```
  implicit val fixedValuesParameterEditorDecoder: Decoder[FixedValuesParameterEditor] =
    Decoder.forProduct2("possibleValues", "mode")(FixedValuesParameterEditor.apply)
      .or(Decoder.forProduct1("possibleValues")(FixedValuesParameterEditor(_, FixedValuesEditorMode.LIST)))
```

2024-12-20 11:12 UTC, mgoworko commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
> +  def activityParametersDefinition: Map[String, Map[String, ParameterConfig]]
Maybe it would be a good idea to define enum (sealed trait) with all possible scenario actions in the API module and make it the key of this map. Right now if we change the name of some scenario action, the change will not be enforceable by compiler in all implementations of this trait.

2024-12-20 11:12 UTC, mgoworko commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newactivity/ActivityInfoService.scala
> +class ActivityInfoService(activityInfoProvider: ActivityInfoProvider, processResolver: UIProcessResolver) {
Comment about naming convention: I think that in this context the name "Scenario action" should be used. Deploy/cancel and others are scenario actions, not activities from what I know. I can be especially confusing now, when ScenarioActivities exist in different context.

2024-12-20 11:12 UTC, mgoworko commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ActivityInfoResources.scala
> +  def securedRoute(implicit user: LoggedUser): Route = {
We discussed returning this information in the already existing endpoint /process/{name}/"status". I think that it would be a good idea, but I'm not sure if it would be easy or doable without making some POC. If not possible, then I think the new service should be a Tapir service, with "ActionInfo" in name instead of "ActivityInfo"

2025-01-09 17:10 UTC, gskrobisz commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newactivity/ActivityInfoService.scala
> +class ActivityInfoService(activityInfoProvider: ActivityInfoProvider, processResolver: UIProcessResolver) {
Renamed: activity -> action

2025-01-09 17:12 UTC, gskrobisz commented on common-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/FixedExpressionValue.scala
> +  def apply(expression: String, label: String): FixedExpressionValue = FixedExpressionValue(expression, label, None)
Reverted hintText (YAGNI) and this change here is no longer required.

2025-01-10 12:56 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +  implicit val fixedValuesParameterEditorDecoder: Decoder[FixedValuesParameterEditor] = { (c: HCursor) =>
Fixed.

2025-01-13 09:49 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/component/NodesDeploymentData.scala
> +  type NodeDeploymentData = Map[String, String]
Confirmed with arkadius to keep Map (for now, maybe changed later).

2025-01-13 11:25 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
> +  def activityParametersDefinition: Map[String, Map[String, ParameterConfig]]
I've found better place for this trait (close to ProcessAction) and used ScenarioActionName and ParameterName instead of String.

2025-01-16 00:18 UTC, gskrobisz commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ActivityInfoResources.scala
> +  def securedRoute(implicit user: LoggedUser): Route = {
Fixed: replaced with tapir endpoint.

2025-01-21 09:43 UTC, mgoworko commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newactivity/ActivityInfoService.scala
> +class ActivityInfoService(activityInfoProvider: ActivityInfoProvider, processResolver: UIProcessResolver) {
"activity" is still used in some contexts, such as `nodeToActivityToParameters`, FE `const activityParameters`, `const activityNodeParameters` and possibly some more usages.

2025-01-21 11:28 UTC, Dzuming requested changes
I left some comments

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
> +    const mode = FixedValuesEditorMode[editorConfig.mode || "LIST"];
What's the reason for introducing editor mode concept instead of adding a new editor

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/toolbars/scenarioActions/buttons/DeployButton.tsx
> +    // TODO: find better place to reload activity capabilities and properties
What about this todo, will you resolve it in this pr?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +                {activityNodeParameters.map((anp: ActionNodeParameters) => (
This acronym was a little confusing to me. I needed to go back to activityNodeParameters to understand what was going on. WDYT about renaming it to activityNodeParameter?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +                        Advanced parameters
Missing i18n

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/ActionParameter.tsx
> +    nodeName: string;
should it be nodeName or nodeId?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/ActionParameter.tsx
> +    const onValueChange = useCallback((newValue) => onChange(nodeName, propertyName, newValue), [onChange, nodeName, propertyName]);
missing newValue type

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/ActionParameter.tsx
> +    const current = nodesData[nodeName][propertyName] || "";
Maybe it's worth renaming it to currentNodePropertyName for readability sake?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    // TODO: get rid of meta
Are you going to resolve this TODO in this pr?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    const activityNodeParameters = activityParameters["DEPLOY"] || ([] as ActionNodeParameters[]);
Can you add useMemo here?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    const [values, setValues] = useState(initialValues);
Can we simplify it?

const [values, setValues] = useState(() => initialNodesData(activityNodeParameters));

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    }, [action, comment, dispatch, processName, props]);
Missing values dependency here

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/modals/GenericAction/useActionCapabilities.tsx
> +export function useActionCapabilities() {
Can you add blank line before import?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/toolbars/scenarioActions/buttons/DeployButton.tsx
> +    const action = (p, c, d) => HttpService.deploy(p, c, d).finally(() => dispatch(loadProcessState(processName, processVersionId)));
Can we find a better name for these (p, c, d) parameters?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/components/toolbars/scenarioActions/buttons/RunOffScheduleButton.tsx
> +    const action = (p, c, d) => HttpService.runOffSchedule(p, c).finally(() => dispatch(loadProcessState(processName, processVersionId)));
Can we find a better name for these (p, c, d) parameters?

2025-01-21 11:28 UTC, Dzuming commented on designer/client/src/http/HttpService.ts
> +        const runDeploymentRequest = {
Can't we just simplify it to

const runDeploymentRequest = { nodesDeploymentData, comment };
?

Undefined values will be removed automatically from a JSON.

Alternatively, if we want to do it explicitly, maybe can we use lodash?

const runDeploymentRequest = _.pickBy({comment, nodesDeploymentData});

2025-01-24 10:41 UTC, mateuszkp96 requested changes

2025-01-24 10:41 UTC, mateuszkp96 commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +  }
Here you can use  `Encoder.encodeString.contramap(_.name())`

2025-01-24 10:41 UTC, mateuszkp96 commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +object FixedValuesParameterEditor {
Let's move the object definition below the class definition

2025-01-24 10:41 UTC, mateuszkp96 commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +    mode: FixedValuesEditorMode = FixedValuesEditorMode.LIST
IMO we can remove default value here as we have a dedicated apply method for such case

2025-01-24 10:41 UTC, mateuszkp96 commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
> +import pl.touk.nussknacker.engine.api.component.{Component, ParameterConfig, ProcessingMode}
Not used

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/client/src/actions/actionTypes.ts
> +    | "UPDATE_ACTION_PARAMETERS"
As discussed, it seems that we can remove this action and fetch the action parameters in the DeployWithParametersDialog

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
> +  }
Can it be defined in the `server` module? The other classes in this package relates to UIDefinitions, and this class not

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
> +                    reject(MalformedRequestContentRejection("lorem ipsum", notValidDeployRequest))
`lorem ipsum` left

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/ActionInfoEndpoints.scala
> +          jsonBody[UiActionParameters]
WDYT about introducing Response class?  It will be easier to maintain in case of API changes

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/server/src/test/scala/pl/touk/nussknacker/ui/api/ActionInfoResourcesSpec.scala
> +          notNullValue(),
WDYT about using equalsJson here?

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ActionInfoHttpService.scala
> +            scenarioGraph,
As discussed we can get `ScenarioGraph` from `scenarioWithDetails`

2025-01-24 10:41 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/ActionInfoEndpoints.scala
> +      )
We can remove body and change HTTP method to GET

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryIntegrationSpec.scala
> +import pl.touk.nussknacker.engine.kafka.source.flink.FlinkKafkaSource.OffsetResetStrategy
Not used

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceWithDeploymentParametersSpec.scala
> +    // TODO
TODO left

2025-01-24 10:41 UTC, mateuszkp96 commented on extensions-api/src/main/scala/pl/touk/nussknacker/engine/api/deployment/ProcessAction.scala
> +trait WithActionParametersSupport { self: Source =>
Let's move it below `object ScenarioActionName` to not split the ScenarioActionName definition

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
> +          case _            => list
Let's use None instead of _

2025-01-24 10:41 UTC, mateuszkp96 commented on scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/activity/ModelDataActionInfoProvider.scala
> +        case _                                     => Map.empty
Let's use Invalid instead of _

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
> +  val OFFSET_PARAMETER_NAME: ParameterName = ParameterName("offset")
private?

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
> +          case _            => list
case None

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +      case _ => ()
OffsetResetStrategy.Continue

2025-01-24 10:41 UTC, mateuszkp96 commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +  }
Can it be changed to Enumeratum? Unfortunately, a Scala Enumeration type does not support exhaustive pattern matching

2025-01-24 10:41 UTC, mateuszkp96 commented on scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/test/ModelDataTestInfoProvider.scala
> +    with LazyLogging {
expressionCompiler and nodeCompiler defined below are not used anymore

2025-01-24 10:41 UTC, mateuszkp96 commented on scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/activity/CommonModelDataInfoProvider.scala
> +class CommonModelDataInfoProvider(modelData: ModelData) {
WDYT about making it abstract? It does not expose any public method

2025-01-28 13:12 UTC, piotrp commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +                  OffsetResetStrategy.Reset.toString,
Maybe we should rename `Reset` to `Latest` and `Restart` to `Earliest`? IMO current names are confusing, because Kafka has its own `auto.offset.reset`, with `latest`, `earliest` and `none` values.

2025-01-28 13:18 UTC, piotrp commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +                  "Start reading new events only (reset)."
"reset" and "restart" are confusing for me, both mean basically the same. From Merriam-Webster:

>reset
> : to change the reading of often to zero
> reset an odometer

> restart
> : to start anew

2025-01-28 13:31 UTC, piotrp commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +          label = Some("Offset reset strategy"),
How about "Reset offsets", with descriptions:
- No, continue from the last known position
- Yes, read only events added after this scenario is deployed
- Yes, read all events from the topic

2025-01-28 13:39 UTC, piotrp commented
I see that the code path used to process the `forceLatestRead` is unused (the `setToLatestOffsetIfNeeded` is no longer used in your branch), but you haven't removed this parameter

2025-02-04 22:05 UTC, gskrobisz commented on designer/client/src/components/graph/node-modal/editors/expression/FixedValuesEditor.tsx
> +    const mode = FixedValuesEditorMode[editorConfig.mode || "LIST"];
For a brief moment it seemed to be an easier approach. Fixed by adding a new editor.

2025-02-04 22:06 UTC, gskrobisz commented on designer/client/src/components/toolbars/scenarioActions/buttons/DeployButton.tsx
> +    // TODO: find better place to reload activity capabilities and properties
Fixed: moved into DeployWithParamsDialog.

2025-02-04 22:06 UTC, gskrobisz commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +                {activityNodeParameters.map((anp: ActionNodeParameters) => (
Fixed.

2025-02-04 22:07 UTC, gskrobisz commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +                        Advanced parameters
Fixed, wrapped with `t(...)`

2025-02-04 22:07 UTC, gskrobisz commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    }, [action, comment, dispatch, processName, props]);
Fixed.

2025-02-04 22:07 UTC, gskrobisz commented on designer/client/src/components/modals/GenericAction/useActionCapabilities.tsx
> +export function useActionCapabilities() {
Fixed.

2025-02-04 22:08 UTC, gskrobisz commented on designer/client/src/components/toolbars/scenarioActions/buttons/DeployButton.tsx
> +    const action = (p, c, d) => HttpService.deploy(p, c, d).finally(() => dispatch(loadProcessState(processName, processVersionId)));
Fixed, full parameter names.

2025-02-04 22:09 UTC, gskrobisz commented on designer/client/src/components/toolbars/scenarioActions/buttons/RunOffScheduleButton.tsx
> +    const action = (p, c, d) => HttpService.runOffSchedule(p, c).finally(() => dispatch(loadProcessState(processName, processVersionId)));
Fixed, full parameter names.

2025-02-04 22:19 UTC, gskrobisz commented on designer/client/src/http/HttpService.ts
> +        const runDeploymentRequest = {
The concept was to "append" property with key "comment" and value of comment when value of comment is defined. 

E.g. to keep clean deploy request, in `{ comment: someValue }` I want to have either `{ comment: "this is text" }` or no propery at all  when undefined `{  }`.

2025-02-04 22:20 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +  }
Fixed, removed FixedValuesEditorMode, encoder is no longer needed.

2025-02-04 22:20 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +object FixedValuesParameterEditor {
Moved below.

2025-02-04 22:20 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/definition/ParameterEditor.scala
> +    mode: FixedValuesEditorMode = FixedValuesEditorMode.LIST
Fixed, removed FixedValuesEditorMode, default value is no longer needed.

2025-02-04 22:21 UTC, gskrobisz commented on components-api/src/main/scala/pl/touk/nussknacker/engine/api/process/Source.scala
> +import pl.touk.nussknacker.engine.api.component.{Component, ParameterConfig, ProcessingMode}
Fixed.

2025-02-04 22:21 UTC, gskrobisz commented on designer/client/src/actions/actionTypes.ts
> +    | "UPDATE_ACTION_PARAMETERS"
Fixed, dispatcher action is removed, fetching parameters is moved to DeployWithParametersDialog.

2025-02-04 22:22 UTC, gskrobisz commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ManagementResources.scala
> +                    reject(MalformedRequestContentRejection("lorem ipsum", notValidDeployRequest))
Fixed.

2025-02-04 22:23 UTC, gskrobisz commented on engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceWithDeploymentParametersSpec.scala
> +    // TODO
Fixed.

2025-02-04 22:23 UTC, gskrobisz commented on engine/flink/kafka-components-utils/src/test/scala/pl/touk/nussknacker/engine/kafka/source/flink/KafkaSourceFactoryIntegrationSpec.scala
> +import pl.touk.nussknacker.engine.kafka.source.flink.FlinkKafkaSource.OffsetResetStrategy
Fixed.

2025-02-04 22:23 UTC, gskrobisz commented on engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
> +          case _            => list
Fixed.

2025-02-04 22:24 UTC, gskrobisz commented on scenario-compiler/src/main/scala/pl/touk/nussknacker/engine/definition/activity/ModelDataActionInfoProvider.scala
> +        case _                                     => Map.empty
There can be Valid match when `s` is is not `WithActionParametersSupport`. Hence `_`

2025-02-04 22:25 UTC, gskrobisz commented on engine/flink/management/dev-model/src/main/scala/pl/touk/nussknacker/engine/management/sample/source/BoundedSource.scala
> +  val OFFSET_PARAMETER_NAME: ParameterName = ParameterName("offset")
Private.

2025-02-04 22:27 UTC, gskrobisz commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +                  OffsetResetStrategy.Reset.toString,
Renamed strategies to: ToEarliest, ToLatest, None.

2025-02-04 22:33 UTC, gskrobisz commented on nussknacker-dist/src/universal/conf/dev-application.conf
> +            forceLatestRead: true
Rename to `defaultOffsetResetStrategy: "ToLatest"`

2025-02-05 10:47 UTC, Dzuming requested changes
I left a few comments, and there are still existing comments that have not been addressed.

2025-02-05 10:47 UTC, Dzuming commented on designer/client/src/http/HttpService.ts
> +        const runDeploymentRequest = {
yes, I just wanted to point out that we have two IMO more readable approaches to it, explicitly with lodash or implicitly with automatically removing undefined properties by JSON

2025-02-05 10:47 UTC, Dzuming commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +        const response = await HttpService.getActionParameters(processName, scenarioGraph);
Maybe it's worth introducing some loader indicator here, and display content only, when the initial values are correctly set. Also, what about an error scenario where FE could not get actionParameters?

2025-02-05 17:30 UTC, gskrobisz commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +    // TODO: get rid of meta
I'd rather change it in separate PR. This is the same "TODO" as in GenericConfirmDialog and DeployProcessDialog.

2025-02-05 20:14 UTC, gskrobisz commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/newactivity/ActivityInfoService.scala
> +class ActivityInfoService(activityInfoProvider: ActivityInfoProvider, processResolver: UIProcessResolver) {
Fixed.

2025-02-05 20:15 UTC, gskrobisz commented on designer/client/src/components/modals/ActionParameter.tsx
> +    nodeName: string;
Fixed (that one and other names in this file too).

2025-02-05 20:16 UTC, gskrobisz commented on designer/client/src/components/modals/ActionParameter.tsx
> +    const current = nodesData[nodeName][propertyName] || "";
Fixed (removed whole nodesData, it is not necessary here).

2025-02-05 20:17 UTC, gskrobisz commented on designer/client/src/http/HttpService.ts
> +        const runDeploymentRequest = {
Fixed (the first option without lodash) and tested, works perfectly, thanks for the hint :)

2025-02-05 20:23 UTC, gskrobisz commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +          label = Some("Offset reset strategy"),
I've chosen similar descriptions :) Please check if it looks better. Some guys insisted on "strategy" in the name of the parameter (it sounds technically correct, but might be obscure for some people).

2025-02-05 23:26 UTC, gskrobisz commented on designer/restmodel/src/main/scala/pl/touk/nussknacker/restmodel/definition/package.scala
> +  }
Moved to `designer`, close to endpoint definitions.

2025-02-06 12:24 UTC, piotrp commented on docs/integration/KafkaIntegration.md
> +| kafkaEspProperties.defaultOffsetResetStrategy                               | Medium     | boolean  | None          | If scenario is restarted, should offsets of source consumers be reset to latest
We should document possible values

2025-02-06 12:30 UTC, piotrp commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +          label = Some("Offset reset strategy"),
Shouldn't we use the word "messages" here, instead of "events"? 

And the "Start" word is IMO superfluous, we can just say "Read new events (-> messages) only"?

2025-02-06 14:57 UTC, mateuszkp96 requested changes

2025-02-06 14:57 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ActionInfoService.scala
> +  case class UiActionParameters(nameToParameterses: Map[ScenarioActionName, List[UiActionNodeParameters]])
`nameToParameterses` => `nameToParameters`
These classes are used as dtos in `ActionInfoEndpoints`, but such dependency shouldn't exist.
Let's introduce dtos in `ActionInfoEndpoints`, and map domain classes to dtos in `ActionInfoHttpService`.

2025-02-06 14:57 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/process/deployment/ActionInfoService.scala
> +    Decoder.decodeMap[ScenarioActionName, List[UiActionNodeParameters]].map(UiActionParameters)
`@JsonCodec` should be fine for `UiActionParameters`. Now the `nameToParameters` parameter is skipped in the response schema

2025-02-06 14:57 UTC, mateuszkp96 commented on docs/integration/KafkaIntegration.md
> +| kafkaEspProperties.defaultOffsetResetStrategy                               | Medium     | boolean  | None          | If scenario is restarted, should offsets of source consumers be reset to latest
The new type is `string`, let's list all available options in the description

2025-02-06 14:57 UTC, mateuszkp96 commented on designer/client/src/http/HttpService.ts
> +        console.log(runDeploymentRequest);
console.log left

2025-02-06 14:57 UTC, mateuszkp96 commented on nussknacker-dist/src/universal/conf/dev-application.conf
> +          }
Please change `true` to valid strategy name

2025-02-06 14:57 UTC, mateuszkp96 commented on engine/flink/kafka-components-utils/src/main/scala/pl/touk/nussknacker/engine/kafka/source/flink/FlinkKafkaSource.scala
> +  private val defaultOffsetResetStrategy = kafkaConfig.defaultOffsetResetStrategy.getOrElse(OffsetResetStrategy.None)
Let's add annotation here:
  `private val defaultOffsetResetStrategy: OffsetResetStrategy` - you will see that
  kafkaConfig.defaultOffsetResetStrategy has type org.apache.kafka.clients.consumer.OffsetResetStrategy

2025-02-06 14:57 UTC, mateuszkp96 commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/description/ActionInfoEndpoints.scala
> +  implicit val uiActionParametersSchema: Schema[UiActionParameters] = Schema.anyObject
WDYT about such schema? 
```
  implicit val uiActionParametersSchema: Schema[UiActionParameters] = {
    implicit val nodeIdSchema: Schema[NodeId]                   = Schema.string
    implicit val scenarioActionName: Schema[ScenarioActionName] = Schema.string
    implicit val parameterEditorSchema: Schema[ParameterEditor] =
      NodesApiEndpoints.Dtos.NodeValidationResultDto.parameterEditorSchema
    implicit val parameterSchema: Schema[UiActionParameterConfig]     = Schema.derived
    implicit val nodeParametersSchema: Schema[UiActionNodeParameters] = Schema.derived
    implicit val mapScenarioActionParametersSchema: Schema[Map[ScenarioActionName, List[UiActionNodeParameters]]] =
      Schema.schemaForMap[ScenarioActionName, List[UiActionNodeParameters]](_.value)
    Schema.derived
  }
```

Some code needs to be rearranged in NodeValidationResultDto, but as we don't have a common DTO type for ParameterEditor, IMO we can use the existing schema.
```
    object NodeValidationResultDto {

      implicit lazy val parameterEditorSchema: Schema[ParameterEditor] = {
        implicit lazy val simpleParameterEditorSchema: Schema[SimpleParameterEditor] = Schema.derived
        implicit lazy val dualEditorSchema: Schema[DualEditorMode]                   = Schema.string
        implicit lazy val uiParameterSchema: Schema[UIParameter]                     = Schema.derived
        implicit lazy val durationSchema: Schema[Duration]                           = Schema.schemaForJavaDuration
        implicit lazy val timeSchema: Schema[java.time.temporal.ChronoUnit] = Schema(
          SProduct(
            List(
              SProductField(FieldName("name"), Schema.schemaForString, chronoUnit => Some(chronoUnit.name())),
              SProductField(FieldName("duration"), durationSchema, chronoUnit => Some(chronoUnit.getDuration))
            )
          )
        )
        Schema.derived
      }
      ...
    }  
```

2025-02-07 19:33 UTC, gskrobisz commented on designer/client/src/components/modals/DeployWithParametersDialog.tsx
> +        const response = await HttpService.getActionParameters(processName, scenarioGraph);
I've added loader and showBoundary when FE could not get actionParameters. ErrorBoundary is defined in the same way as in WindowContent. All of it makes that user sees spinner while parameters are loading and user sees big, full screen, error panel when an error occurs.

2025-02-10 11:37 UTC, Dzuming approved these changes
LGTM

2025-02-10 13:03 UTC, mateuszkp96 approved these changes
LGTM

2025-02-11 07:24 UTC, merged