[NU-1772] Deployment comment validation
TouK/nussknacker pull request #7076
Opened 2024-10-24 10:57 UTC by mgoworko

## Describe your changes

## Checklist before merge
- [ ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ ] Code is cleaned from temporary changes and commented out lines
- [ ] Parts of the code that are not easy to understand are documented in the code
- [ ] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [ ] Documentation added or updated
- [ ] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [ ] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

2024-10-24 16:24 UTC, mgoworko commented
I added commit with refactor of non-empty comment handling - the autogenerated apply method was still used in a few places, detected by Cypress tests.

2024-10-25 12:45 UTC, mk-software-pl requested changes

2024-10-25 12:45 UTC, mk-software-pl commented on designer/server/src/test/scala/pl/touk/nussknacker/ui/config/FeatureTogglesConfigTest.scala
> +      .parseResources("config/business-cases/category-used-more-than-once-designer.conf")
why?

2024-10-25 12:45 UTC, mk-software-pl commented on designer/server/src/main/scala/pl/touk/nussknacker/ui/api/ScenarioActivityApiHttpService.scala
> +          validateComment(_, request.commentContent),
I'm not convinced with the current solution.

I see the following problems:
1. The validation should be done in the core layer and the repository layer should not be bothered with this kind of validation. After we validate some comment we should (at the core layer) produce an instance that holds the invariant that proves (to the repository layer) the instance is validated. 

2. The `addNewComment` method adds sth like a simple/regular comment. The `editComment` method modifies a simple/regular comment and deployment comment (this one has different validation rules). We don't have such distinction at the type level, but IMO we should have it. 

3. Comment smart constructor should have a validation logic encapsulated. IMO too much service/core logic is encapsulated in the repository.

2024-10-25 13:28 UTC, mk-software-pl approved these changes
let's address all the comments in a separate PR

2024-10-25 13:29 UTC, merged