[Nu-1889] provide an unique validation message to the scenario label
TouK/nussknacker pull request #7182
Opened 2024-11-20 12:22 UTC by Dzuming

## Describe your changes
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/378b79cd-2959-4db9-91a0-ac75129648f0">

## Checklist before merge
- [ ] Related issue ID is placed at the beginning of PR title in \[brackets\] (can be GH issue or Nu Jira issue)
- [ ] Code is cleaned from temporary changes and commented out lines
- [ ] Parts of the code that are not easy to understand are documented in the code
- [ ] Changes are covered by automated tests
- [ ] Showcase in dev-application.conf added to demonstrate the feature
- [ ] Documentation added or updated
- [ ] Added entry in _Changelog.md_ describing the change from the perspective of a public distribution user
- [ ] Added _MigrationGuide.md_ entry in the appropriate subcategory if introducing a breaking change
- [ ] Verify that PR will be squashed during merge

2024-11-20 14:55 UTC, mateuszkp96 requested changes

2024-11-20 14:55 UTC, mateuszkp96 commented on designer/client/src/components/toolbars/scenarioDetails/ScenarioLabels.tsx
> +const labelUniqueValidation = (label: string) => ({ label, messages: ["This label already exists. Please enter a unique value."] });
Let's add the `i18next.t` option

2024-11-21 07:20 UTC, Dzuming commented on designer/client/src/components/toolbars/scenarioDetails/ScenarioLabels.tsx
> +const labelUniqueValidation = (label: string) => ({ label, messages: ["This label already exists. Please enter a unique value."] });
Done ✔️

2024-11-21 07:23 UTC, mateuszkp96 approved these changes

2024-11-21 08:17 UTC, arkadius approved these changes

2024-11-21 08:19 UTC, merged